Repository techlauncher-mlai-edge-physics/CFlowSim, pull requests merged in 2023-08, with the labels that each got.

#24 ci(actions): create github action files
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .github/workflows/changelog.yml
  .github/workflows/codeql.yml
  CHANGELOG.md
Labels: enhancement

#26 docs(ISSUE_TEMPLATE): add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/risk-log.md
Labels: documentation, Severity: Low

#44 feat(about): added some styling to about page and read from `README.md`
  README.md
  docs/about.md
  docs/gettingstarted.md
  src/components/NavBar.tsx
  src/pages/about.tsx
Labels: category:website

#45 feat(website): implement the responsive design
  src/components/NavBar.tsx
  src/components/ParametersBar.tsx
  src/pages/index.tsx
Labels: category:website

#53 refactor(styles): remove deprecated style sheets
  package-lock.json
  package.json
  src/styles/AboutPage.module.css
  src/styles/Button.module.scss
  src/styles/Home.module.css
  src/styles/app.css
  src/styles/theme/Global.js
  src/styles/theme/ThemeSwitching.styled.ts
Labels: category:website
